# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1551079e9ea38c8baa38a95470f9de4169c0eb72dcf5360fae31f368d5d4401261a4ae2c1a8e1af100dbb49609172de55cd64a9ad41adfd470791d69f4a5c092

test:
  secret_key_base: 4fd09039d95ac29688fba82463faa30fab5521feb87b21d42a3a5b0a3be8104331e0284caf2477cbb1eaa774d6656172040402228be8539ce19d0b1dc4743e6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
